// The Bun.YAML.parse corpus: 150 inputs spanning the frontmatter shapes the
// bundle actually feeds the parser, the scalar-typing edges of the YAML 1.2
// core schema, block scalars, flow collections, and the constructs this shim
// deliberately refuses.
//
// Bun is the oracle. Nothing here records an expected answer - the answers are
// whatever Bun says, captured at test time, so a Bun release that changes the
// parse moves both sides at once.

module.exports =[
  "name: foo",
  "name: foo\ndescription: does a thing",
  "name: foo\n\ndescription: blank line between",
  "description: with: an inner colon",
  "allowed-tools: Read, Write, Bash",
  "tools:\n  - Read\n  - Write",
  "tools:\n- Read\n- Write",
  "nested:\n  a: 1\n  b: 2",
  "deep:\n  mid:\n    leaf: x",
  "list_of_maps:\n  - a: 1\n    b: 2\n  - a: 3",
  "empty_value:",
  "empty_value:\nnext: 1",
  "n: 1",
  "n: -1",
  "n: 1.5",
  "n: 1e3",
  "n: 0x10",
  "n: 0o17",
  "n: 007",
  "b: true",
  "b: false",
  "b: True",
  "b: TRUE",
  "b: yes",
  "b: no",
  "b: on",
  "b: off",
  "z: null",
  "z: ~",
  "z: Null",
  "z: NULL",
  "s: 'single'",
  "s: \"double\"",
  "s: unquoted words",
  "s: 'it''s'",
  "s: \"a\\nb\"",
  "s: \"tab\\there\"",
  "s: ''",
  "s: \"\"",
  "s: 2026-08-26",
  "s: 12:30",
  "s: +1",
  "s: .5",
  "s: 1_000",
  "s: [1, 2, 3]",
  "s: {a: 1, b: 2}",
  "s: []",
  "s: {}",
  "s: # comment only",
  "a: 1 # trailing comment",
  "# leading comment\na: 1",
  "s: |\n  line one\n  line two",
  "s: >\n  folded one\n  folded two",
  "s: |-\n  stripped",
  "s: |+\n  kept\n",
  "---\na: 1",
  "---\na: 1\n---\nb: 2",
  "a: &anchor 1\nb: *anchor",
  "a: !!str 1",
  "? complex\n: key",
  "- just\n- a\n- list",
  "just a scalar",
  "",
  "\n",
  "   ",
  "a: 1\n\tb: 2",
  "a: [1, 2",
  "a: 'unterminated",
  "  a: 1\nb: 2",
  "a: 1\n b: 2",
  "a:\n- 1\n  - 2",
  "n: .inf",
  "n: -.inf",
  "n: .nan",
  "n: .INF",
  "n: .NaN",
  "n: 0b101",
  "n: 1.0",
  "n: -0",
  "n: 1.",
  "n: +.5",
  "n: 1e-3",
  "n: 1E3",
  "n: 12345678901234567890",
  "n: 0",
  "n: 00",
  "s: a#b",
  "s: a #b",
  "s: a # b",
  "s: \"a # b\"",
  "s: '# not a comment'",
  "s: -",
  "s: --",
  "s: -x",
  "s: a-b",
  "s: :x",
  "s: x:",
  "s: 'x: y'",
  "s: @at",
  "s: `tick",
  "s: %pct",
  "s: a,b",
  "s: a|b",
  "s: a>b",
  "s:    spaced   value   ",
  "s: trailing   ",
  "s: \\u00e9clair",
  "s: \u65e5\u672c\u8a9e",
  "s: emoji_here",
  "\"quoted key\": 1",
  "'single key': 1",
  "key-with-dash: 1",
  "key_under: 1",
  "UPPER: 1",
  "a b: 1",
  "1: numeric key",
  "true: bool key",
  "a: 1\na: 2",
  "a:\n  - 1\n  - 2\nb: 3",
  "a:\n  - - 1\n    - 2",
  "a:\n  b:\n    - 1",
  "- a: 1\n  b: 2\n- c: 3",
  "a:\n    deep: 4space",
  "a:\n  b: 1\n  c:\n    d: 2\ne: 3",
  "list:\n  -   spaced\n  -   items",
  "a: []\nb: {}",
  "a: [ 1 , 2 ]",
  "a: { x : 1 }",
  "a: [a, 'b', \"c\"]",
  "a: [[1,2],[3]]",
  "a: {b: {c: 1}}",
  "s: >-\n  folded stripped",
  "s: >+\n  folded kept\n",
  "s: |\n  a\n\n  b",
  "s: |\n    four space base",
  "s: |2\n   explicit indent",
  "s: |\n  line\nnext: 1",
  "---",
  "--- \n",
  "a: 1\n...",
  "\n\na: 1\n\n",
  "a: 1\r\nb: 2",
  "# only a comment",
  "a: 1\n# mid comment\nb: 2",
  "a: !custom 1",
  "a: !!int '3'",
  "&a x",
  "a: &x {b: 1}\nc: *x",
  "<<: *base\na: 1",
  "? [a, b]\n: c",
  "description: Don't use this # deprecated",
  "s: a\"b # c",
  "title: It's fine",
  "n: -0x10",
  "n: -0o17",
  "n: +0x10",
  "--- scalar",
  "--- [1, 2]",
  "--- |\n  text",
  "{a: 1}",
  "[a: 1]",
  "{a: 1,\nb: 2}",
  "{a:1}",
  "[1, 2]",
  "s: >\n  a\n    more\n  b",
  "s: >\n  a\n  b\n    deeper",
  "\"a: 1",
  "\"a\" x: 1",
  "s: | junk\n  body",
  "s: > junk\n  body",
  "a: - item",
  "s: >\nnext: 1",
  "s: |\nnext: 1",
  "{[1]: x}",
  "{x}: 1",
  "[]: 1",
  "s: 38;5;208",
  "key: a:b"
];
